server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5434/task_user_service
    password: Dang972004@
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
