server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/task_user_service
    username: root
    password: Dang972004@
    driver-class-name: com.mysql.cj.jdbc.Driver
